index:
    path: /
    controller: App\Controller\TestController::index

product_index:
    path: /products/
    controller: App\Controller\ProductController::index
    methods: [GET]

product_create:
    path: /products/
    controller: App\Controller\ProductController::create
    methods: [POST]

product_edit:
    path: /products/{id}
    controller: App\Controller\ProductController::edit
    methods: [PATCH]

product_retrieve:
    path: /products/{id}
    controller: App\Controller\ProductController::retrieve
    methods: [GET]

auth_steam_redirect:
    path: /auth/steam/redirect
    controller: App\Controller\AuthController::steamAuthRedirect

auth_steam_verify:
    path: /auth/steam/verify
    controller: App\Controller\AuthController::steamAuthVerify
    methods: [POST]